import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Stack, Typography } from '@mui/material';
import { BiTask } from 'react-icons/bi';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Tasks manager</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<main className={inter.className}>
				<Stack gap={2} direction={'row'}>
					<Typography>Hello MUI world</Typography>
					<BiTask />
				</Stack>
			</main>
		</>
	);
}
