import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Stack, Typography } from '@mui/material';
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import { GetServerSideProps } from 'next';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const router = useRouter();

	useEffect(() => {
		// Redirect to '/tasks' when the component mounts
		router.push('/tasks');
	}, []);

	return (
		<>
			<Head>
				<title>Tasks manager</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<main className={inter.className}>
				<Stack gap={2} direction={'row'}>
					<Typography>Home Page</Typography>
				</Stack>
			</main>
		</>
	);
}

export const getServerSideProps: GetServerSideProps = async () => {
	return {
		redirect: {
			destination: '/tasks',
			permanent: false, // Set to true if the redirection is permanent
		},
	};
};
