import { CreateEditTaskFormModal } from '@/components/createEditTaskFormModal';
import { CustomButton } from '@/components/customs';
import { CustomMultiSelectInput } from '@/components/customs';
import { CustomLoader } from '@/components/customs';
import { EmptyTaskList } from '@/components/emptyTaskList';
import { TaskLists } from '@/components/taskLists';
import { FAILED_TO_FETCH_MESSAGE, STATUS_LIST } from '@/constants';
import { useGetAllTaskData } from '@/hooks';
import { TaskListQuery } from '@/types';
import { Box, Stack, TextField, Typography } from '@mui/material';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { useState } from 'react';
import { BiFilterAlt } from 'react-icons/bi';
import { toast } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] });

const Tasks = () => {
	const [isOpenCreateEditTaskForm, setIsOpenCreateEditTaskForm] = useState(false);
	const [isShowFilters, setIsShowFilters] = useState(false);
	const [filterValues, setFilterValues] = useState<TaskListQuery | null>(null);
	const { allTasks, isLoadingTasks, tasksFetchingError, refetchAllTasks } = useGetAllTaskData(filterValues);

	const handleFiltering = (fieldName: keyof TaskListQuery, value: any) => {
		setFilterValues({
			[fieldName]: value,
		});
	};

	if (tasksFetchingError) {
		toast.error(tasksFetchingError.message || FAILED_TO_FETCH_MESSAGE);
	}

	const toggleShowCreatEditTaskForm = () => {
		setIsOpenCreateEditTaskForm((prev) => !prev);
	};

	const toggleIsShowFilters = () => {
		setIsShowFilters((prev) => !prev);
	};

	return (
		<>
			<Head>
				<title>List of Tasks</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<main className={inter.className}>
				<Stack padding={4} direction={'column'} rowGap={3} width={'80%'}>
					<Stack direction={'row'} alignItems={'center'} gap={2}>
						<Typography variant="h5" fontSize={22} fontWeight={'600'}>
							Tasks
						</Typography>
						<CustomButton btnType="tertiary" btnText="New Task" onClick={toggleShowCreatEditTaskForm} />
						<CustomButton
							startIcon={<BiFilterAlt />}
							btnType="primary"
							btnText="Filters"
							onClick={toggleIsShowFilters}
						/>
					</Stack>
					{isShowFilters && (
						<Stack gap={2} alignItems={'center'} direction={'row'} width={'100%'}>
							<Box border={'1px solid #10182808'} bgcolor={'#EEF2F8'} p={1} borderRadius={2} width={'100%'}>
								<Stack direction={'row'} gap={3} alignItems={'center'}>
									<TextField
										variant="outlined"
										size="small"
										fullWidth
										placeholder="Filter by title and assignee name"
										onChange={(e) => {
											handleFiltering('search', e.target.value);
										}}
										value={filterValues?.search || ''}
									/>
									<CustomMultiSelectInput
										size="small"
										label="Statuses"
										options={STATUS_LIST}
										getValue={(value) => {
											handleFiltering('status', value);
										}}
										value={filterValues?.status || []}
									/>
									<CustomButton btnType="primary" btnText="Clear" onClick={() => setFilterValues(null)} />
								</Stack>
							</Box>
						</Stack>
					)}
					<CustomLoader key={`${isLoadingTasks}`} loading={isLoadingTasks} />
					{allTasks && allTasks.length ? <TaskLists taskLists={allTasks} /> : isLoadingTasks ? null : <EmptyTaskList />}
				</Stack>
			</main>
			<CreateEditTaskFormModal
				isOpen={isOpenCreateEditTaskForm}
				handleCloseModal={toggleShowCreatEditTaskForm}
				refetchAllTasks={refetchAllTasks}
				key={`${isOpenCreateEditTaskForm}`}
			/>
		</>
	);
};

export default Tasks;
