import { CreateEditTaskFormModal } from '@/components/createEditTaskFormModal';
import CustomButton from '@/components/customs/Button';
import { CustomLoader } from '@/components/customs/Loader';
import { TaskLists } from '@/components/taskLists';
import { FAILED_TO_FETCH_MESSAGE } from '@/constants';
import { useGetAllTaskData } from '@/hooks';
import { Stack, Typography } from '@mui/material';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import { useState } from 'react';
import { toast } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] });

const Tasks = () => {
	const { allTasks, isLoadingTasks, tasksFetchingError, refetchAllTasks } = useGetAllTaskData();
	const [isOpenCreateEditTaskForm, setIsOpenCreateEditTaskForm] = useState(false);

	if (tasksFetchingError) {
		toast.error(tasksFetchingError.message || FAILED_TO_FETCH_MESSAGE);
	}

	const toggleShowCreatEditTaskForm = () => {
		setIsOpenCreateEditTaskForm((prev) => !prev);
	};

	return (
		<>
			<Head>
				<title>List of Tasks</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>
			<main className={inter.className}>
				<Stack padding={4} direction={'column'} rowGap={3} width={'80%'}>
					<Stack direction={'row'} alignItems={'center'} gap={2}>
						<Typography variant="h5" fontSize={22} fontWeight={'600'}>
							Tasks
						</Typography>
						<CustomButton btnType="tertiary" btnText="New Task" onClick={toggleShowCreatEditTaskForm} />
					</Stack>
					<CustomLoader key={`${isLoadingTasks}`} loading={isLoadingTasks} />
					{allTasks && allTasks.length ? <TaskLists taskLists={allTasks} /> : null}
				</Stack>
			</main>
			<CreateEditTaskFormModal
				isOpen={isOpenCreateEditTaskForm}
				handleCloseModal={toggleShowCreatEditTaskForm}
				refetchAllTasks={refetchAllTasks}
				key={`${isOpenCreateEditTaskForm}`}
			/>
		</>
	);
};

export default Tasks;
